# Customer churn prediction

In [1]:
def warn(*arg,**kwarg):
    pass
import warnings
warnings.warn = warn

In [2]:
# importing libreries

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [4]:
#  Loading dataset

In [5]:
churn_data = pd.read_csv('Desktop/Churn_Modelling.csv', encoding = 'utf-8')

In [6]:
churn_data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
# information about dataset

In [8]:
churn_data.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [9]:
churn_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [10]:
churn_data1 = churn_data.drop(['Surname','Geography'], axis = 1)

In [11]:
churn_data1.head()

RowNumber  CustomerId  CreditScore  Gender  Age  Tenure    Balance  \
0          1    15634602          619  Female   42       2       0.00   
1          2    15647311          608  Female   41       1   83807.86   
2          3    15619304          502  Female   42       8  159660.80   
3          4    15701354          699  Female   39       1       0.00   
4          5    15737888          850  Female   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0              1          1               1        101348.88       1  
1              1          0               1        112542.58       0  
2              3          1               0        113931.57       1  
3              2          0               0         93826.63       0  
4              1          1               1         79084.10       0

In [12]:
churn_data1['Gender'] = pd.get_dummies(churn_data1['Gender'],drop_first = True)
churn_data1.head()

RowNumber  CustomerId  CreditScore  Gender  Age  Tenure    Balance  \
0          1    15634602          619       0   42       2       0.00   
1          2    15647311          608       0   41       1   83807.86   
2          3    15619304          502       0   42       8  159660.80   
3          4    15701354          699       0   39       1       0.00   
4          5    15737888          850       0   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0              1          1               1        101348.88       1  
1              1          0               1        112542.58       0  
2              3          1               0        113931.57       1  
3              2          0               0         93826.63       0  
4              1          1               1         79084.10       0

In [13]:
churn_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   CreditScore      10000 non-null  int64  
 3   Gender           10000 non-null  uint8  
 4   Age              10000 non-null  int64  
 5   Tenure           10000 non-null  int64  
 6   Balance          10000 non-null  float64
 7   NumOfProducts    10000 non-null  int64  
 8   HasCrCard        10000 non-null  int64  
 9   IsActiveMember   10000 non-null  int64  
 10  EstimatedSalary  10000 non-null  float64
 11  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), uint8(1)
memory usage: 869.3 KB


In [14]:
# creating the x and y variables

In [15]:
y = churn_data1['Exited']
x = churn_data1.drop(['Exited'], axis = 1)

In [16]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [17]:
x.head()

RowNumber  CustomerId  CreditScore  Gender  Age  Tenure    Balance  \
0          1    15634602          619       0   42       2       0.00   
1          2    15647311          608       0   41       1   83807.86   
2          3    15619304          502       0   42       8  159660.80   
3          4    15701354          699       0   39       1       0.00   
4          5    15737888          850       0   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0              1          1               1        101348.88  
1              1          0               1        112542.58  
2              3          1               0        113931.57  
3              2          0               0         93826.63  
4              1          1               1         79084.10

In [18]:
# Spliting data into train and test sets

In [19]:
X_train , X_test , Y_train , Y_test = train_test_split(x , y , random_state = 42 , test_size = 0.2)

In [20]:
np.sum(y)

2037

In [21]:
np.sum(Y_train)

1644

In [22]:
np.sum(Y_test)

393

In [23]:
# fitting the data to model
scaler = StandardScaler()

In [24]:
X_train_scaled = scaler.fit_transform(X_train)

In [25]:
X_test_scaled = scaler.transform(X_test)

In [26]:
X_train_scaled

array([[ 1.4692775 , -1.24645641,  0.35649971, ...,  0.64920267,
         0.97481699,  1.36766974],
       [-1.19499359,  1.05381124, -0.20389777, ...,  0.64920267,
         0.97481699,  1.6612541 ],
       [-1.15724427,  0.3664786 , -0.96147213, ...,  0.64920267,
        -1.02583358, -0.25280688],
       ...,
       [ 0.13108128, -1.6259648 ,  0.86500853, ..., -1.54035103,
        -1.02583358, -0.1427649 ],
       [-1.43776677,  1.62852321,  0.15932282, ...,  0.64920267,
        -1.02583358, -0.05082558],
       [ 0.78217054,  0.21718071,  0.47065475, ...,  0.64920267,
         0.97481699, -0.81456811]])

In [27]:
X_test_scaled

array([[ 0.42961263, -0.04416715, -0.57749609, ..., -1.54035103,
        -1.02583358, -1.01960511],
       [-0.11342351,  0.64443214, -0.29729735, ...,  0.64920267,
         0.97481699,  0.79888291],
       [-1.1361185 ,  0.43240018, -0.52560743, ...,  0.64920267,
        -1.02583358, -0.72797953],
       ...,
       [ 0.98407747,  0.77960199,  0.81311987, ...,  0.64920267,
        -1.02583358, -1.16591585],
       [-1.35638061, -0.02204946,  0.41876609, ...,  0.64920267,
        -1.02583358, -0.41163463],
       [ 0.66407403, -0.5433811 , -0.24540869, ...,  0.64920267,
         0.97481699,  0.12593183]])

# Logistic Regression

In [28]:
log_reg = LogisticRegression(random_state = 0,
                            C = 1,
                            fit_intercept = True,
                            )
log_reg.fit(X_train_scaled, Y_train)

LogisticRegression(C=1, random_state=0)

In [29]:
log_reg.predict(X_train_scaled)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
log_reg.score(X_train_scaled, Y_train)

0.806875

In [31]:
log_reg.score(X_test_scaled, Y_test)

0.815

In [32]:
accuracy = log_reg.score(X_test, Y_test)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.80


# Random Forest

In [33]:
rf = RandomForestClassifier()
rf.fit(X_train, Y_train)

RandomForestClassifier()

In [34]:
predictions = rf.predict(X_test)
predictions

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [35]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_test, predictions))
print("\n")
print(classification_report(Y_test, predictions))

[[1554   53]
 [ 225  168]]


              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1607
           1       0.76      0.43      0.55       393

    accuracy                           0.86      2000
   macro avg       0.82      0.70      0.73      2000
weighted avg       0.85      0.86      0.85      2000

