# Fraud Prediction

### importing Dependencies

In [1]:
def warn(*args,**kwargs):
    pass
import warnings
warnings.warn = warn

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix

In [3]:
# loading dataset
credit_card_data = pd.read_csv(r'Desktop\fraudTrain.csv',encoding="utf-8")

In [4]:
# first 5 transactions
credit_card_data

Unnamed: 0 trans_date_trans_time               cc_num  \
0                 0   2019-01-01 00:00:18     2703186189652095   
1                 1   2019-01-01 00:00:44         630423337322   
2                 2   2019-01-01 00:00:51       38859492057661   
3                 3   2019-01-01 00:01:16     3534093764340240   
4                 4   2019-01-01 00:03:06      375534208663984   
...             ...                   ...                  ...   
1296670     1296670   2020-06-21 12:12:08       30263540414123   
1296671     1296671   2020-06-21 12:12:19     6011149206456997   
1296672     1296672   2020-06-21 12:12:32     3514865930894695   
1296673     1296673   2020-06-21 12:13:36     2720012583106919   
1296674     1296674   2020-06-21 12:13:37  4292902571056973207   

                                    merchant       category     amt  \
0                 fraud_Rippin, Kub and Mann       misc_net    4.97   
1            fraud_Heller, Gutmann and Zieme    grocery_pos  107.23   
2                       fraud_Lind-Buckridge  entertainment  220.11   
3         fraud_Kutch, Hermiston and Farrell  gas_transport   45.00   
4                        fraud_Keeling-Crist       misc_pos   41.96   
...                                      ...            ...     ...   
1296670                    fraud_Reichel Inc  entertainment   15.56   
1296671             fraud_Abernathy and Sons    food_dining   51.70   
1296672                 fraud_Stiedemann Ltd    food_dining  105.93   
1296673  fraud_Reinger, Weissnat and Strosin    food_dining   74.90   
1296674  fraud_Langosh, Wintheiser and Hyatt    food_dining    4.30   

               first       last gender                         street  ...  \
0           Jennifer      Banks      F                 561 Perry Cove  ...   
1          Stephanie       Gill      F   43039 Riley Greens Suite 393  ...   
2             Edward    Sanchez      M       594 White Dale Suite 530  ...   
3             Jeremy      White      M    9443 Cynthia Court Apt. 038  ...   
4              Tyler     Garcia      M               408 Bradley Rest  ...   
...              ...        ...    ...                            ...  ...   
1296670         Erik  Patterson      M       162 Jessica Row Apt. 072  ...   
1296671      Jeffrey      White      M  8617 Holmes Terrace Suite 651  ...   
1296672  Christopher  Castaneda      M     1632 Cohen Drive Suite 639  ...   
1296673       Joseph     Murray      M           42933 Ryan Underpass  ...   
1296674      Jeffrey      Smith      M           135 Joseph Mountains  ...   

             lat      long  city_pop                                job  \
0        36.0788  -81.1781      3495          Psychologist, counselling   
1        48.8878 -118.2105       149  Special educational needs teacher   
2        42.1808 -112.2620      4154        Nature conservation officer   
3        46.2306 -112.1138      1939                    Patent attorney   
4        38.4207  -79.4629        99     Dance movement psychotherapist   
...          ...       ...       ...                                ...   
1296670  37.7175 -112.4777       258                       Geoscientist   
1296671  39.2667  -77.5101       100   Production assistant, television   
1296672  32.9396 -105.8189       899                    Naval architect   
1296673  43.3526 -102.5411      1126              Volunteer coordinator   
1296674  45.8433 -113.8748       218           Therapist, horticultural   

                dob                         trans_num   unix_time  merch_lat  \
0        1988-03-09  0b242abb623afc578575680df30655b9  1325376018  36.011293   
1        1978-06-21  1f76529f8574734946361c461b024d99  1325376044  49.159047   
2        1962-01-19  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704   
3        1967-01-12  6b849c168bdad6f867558c3793159a81  1325376076  47.034331   
4        1986-03-28  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999   
...             ...                          

In [5]:
# first 5 transactions
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype  
---  ------                 --------------    -----  
 0   Unnamed: 0             1296675 non-null  int64  
 1   trans_date_trans_time  1296675 non-null  object 
 2   cc_num                 1296675 non-null  int64  
 3   merchant               1296675 non-null  object 
 4   category               1296675 non-null  object 
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object 
 7   last                   1296675 non-null  object 
 8   gender                 1296675 non-null  object 
 9   street                 1296675 non-null  object 
 10  city                   1296675 non-null  object 
 11  state                  1296675 non-null  object 
 12  zip                    1296675 non-null  int64  
 13  lat                    1296675 non-null  float64
 14  long              

In [6]:
# last 5 rows
credit_card_data.describe()

Unnamed: 0        cc_num           amt           zip           lat  \
count  1.296675e+06  1.296675e+06  1.296675e+06  1.296675e+06  1.296675e+06   
mean   6.483370e+05  4.171920e+17  7.035104e+01  4.880067e+04  3.853762e+01   
std    3.743180e+05  1.308806e+18  1.603160e+02  2.689322e+04  5.075808e+00   
min    0.000000e+00  6.041621e+10  1.000000e+00  1.257000e+03  2.002710e+01   
25%    3.241685e+05  1.800429e+14  9.650000e+00  2.623700e+04  3.462050e+01   
50%    6.483370e+05  3.521417e+15  4.752000e+01  4.817400e+04  3.935430e+01   
75%    9.725055e+05  4.642255e+15  8.314000e+01  7.204200e+04  4.194040e+01   
max    1.296674e+06  4.992346e+18  2.894890e+04  9.978300e+04  6.669330e+01   

               long      city_pop     unix_time     merch_lat    merch_long  \
count  1.296675e+06  1.296675e+06  1.296675e+06  1.296675e+06  1.296675e+06   
mean  -9.022634e+01  8.882444e+04  1.349244e+09  3.853734e+01 -9.022646e+01   
std    1.375908e+01  3.019564e+05  1.284128e+07  5.109788e+00  1.377109e+01   
min   -1.656723e+02  2.300000e+01  1.325376e+09  1.902779e+01 -1.666712e+02   
25%   -9.679800e+01  7.430000e+02  1.338751e+09  3.473357e+01 -9.689728e+01   
50%   -8.747690e+01  2.456000e+03  1.349250e+09  3.936568e+01 -8.743839e+01   
75%   -8.015800e+01  2.032800e+04  1.359385e+09  4.195716e+01 -8.023680e+01   
max   -6.795030e+01  2.906700e+06  1.371817e+09  6.751027e+01 -6.695090e+01   

           is_fraud  
count  1.296675e+06  
mean   5.788652e-03  
std    7.586269e-02  
min    0.000000e+00  
25%    0.000000e+00  
50%    0.000000e+00  
75%    0.000000e+00  
max    1.000000e+00

In [7]:
credit_card_data = credit_card_data.drop(['merchant','street','city','state','trans_date_trans_time','dob','first','last','trans_num','category','job'],axis=1)
credit_card_data.head()

Unnamed: 0            cc_num     amt gender    zip      lat      long  \
0           0  2703186189652095    4.97      F  28654  36.0788  -81.1781   
1           1      630423337322  107.23      F  99160  48.8878 -118.2105   
2           2    38859492057661  220.11      M  83252  42.1808 -112.2620   
3           3  3534093764340240   45.00      M  59632  46.2306 -112.1138   
4           4   375534208663984   41.96      M  24433  38.4207  -79.4629   

   city_pop   unix_time  merch_lat  merch_long  is_fraud  
0      3495  1325376018  36.011293  -82.048315         0  
1       149  1325376044  49.159047 -118.186462         0  
2      4154  1325376051  43.150704 -112.154481         0  
3      1939  1325376076  47.034331 -112.561071         0  
4        99  1325376186  38.674999  -78.632459         0

In [8]:
credit_card_data['gender'] = pd.get_dummies(credit_card_data['gender'], drop_first =  True)

In [9]:
credit_card_data.head()

Unnamed: 0            cc_num     amt  gender    zip      lat      long  \
0           0  2703186189652095    4.97       0  28654  36.0788  -81.1781   
1           1      630423337322  107.23       0  99160  48.8878 -118.2105   
2           2    38859492057661  220.11       1  83252  42.1808 -112.2620   
3           3  3534093764340240   45.00       1  59632  46.2306 -112.1138   
4           4   375534208663984   41.96       1  24433  38.4207  -79.4629   

   city_pop   unix_time  merch_lat  merch_long  is_fraud  
0      3495  1325376018  36.011293  -82.048315         0  
1       149  1325376044  49.159047 -118.186462         0  
2      4154  1325376051  43.150704 -112.154481         0  
3      1939  1325376076  47.034331 -112.561071         0  
4        99  1325376186  38.674999  -78.632459         0

In [10]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 12 columns):
 #   Column      Non-Null Count    Dtype  
---  ------      --------------    -----  
 0   Unnamed: 0  1296675 non-null  int64  
 1   cc_num      1296675 non-null  int64  
 2   amt         1296675 non-null  float64
 3   gender      1296675 non-null  uint8  
 4   zip         1296675 non-null  int64  
 5   lat         1296675 non-null  float64
 6   long        1296675 non-null  float64
 7   city_pop    1296675 non-null  int64  
 8   unix_time   1296675 non-null  int64  
 9   merch_lat   1296675 non-null  float64
 10  merch_long  1296675 non-null  float64
 11  is_fraud    1296675 non-null  int64  
dtypes: float64(5), int64(6), uint8(1)
memory usage: 110.1 MB


In [11]:
y = credit_card_data['is_fraud']
x = credit_card_data.drop(['is_fraud'], axis = 1)

In [12]:
x.head()

Unnamed: 0            cc_num     amt  gender    zip      lat      long  \
0           0  2703186189652095    4.97       0  28654  36.0788  -81.1781   
1           1      630423337322  107.23       0  99160  48.8878 -118.2105   
2           2    38859492057661  220.11       1  83252  42.1808 -112.2620   
3           3  3534093764340240   45.00       1  59632  46.2306 -112.1138   
4           4   375534208663984   41.96       1  24433  38.4207  -79.4629   

   city_pop   unix_time  merch_lat  merch_long  
0      3495  1325376018  36.011293  -82.048315  
1       149  1325376044  49.159047 -118.186462  
2      4154  1325376051  43.150704 -112.154481  
3      1939  1325376076  47.034331 -112.561071  
4        99  1325376186  38.674999  -78.632459

In [13]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: is_fraud, dtype: int64

In [14]:
X_train , X_test , Y_train , Y_test = train_test_split(x , y , random_state = 42 , test_size = 0.2)

In [15]:
np.sum(y)

7506

In [16]:
np.sum(Y_train)

5986

In [17]:
np.sum(Y_test)

1520

In [18]:
scaler = StandardScaler()

In [19]:
X_train_scaled = scaler.fit_transform(X_train)

In [20]:
X_test_scaled = scaler.transform(X_test)

In [21]:
X_train_scaled

array([[-0.84915931, -0.31864488, -0.40300154, ..., -0.79742859,
        -1.4380815 , -0.08744271],
       [ 0.4018383 , -0.31593235, -0.3167202 , ...,  0.41484723,
         1.72920458, -2.36236846],
       [ 1.63557956,  2.80668465, -0.21767984, ...,  1.67081746,
        -1.28135485, -0.37403537],
       ...,
       [-1.37878785, -0.31590968,  0.3029137 , ..., -1.36729131,
        -0.72182044, -1.16220896],
       [ 0.0616183 , -0.31862539, -0.40874942, ...,  0.06894856,
         1.81416974, -0.52861191],
       [-1.40543102, -0.31861897,  0.44477891, ..., -1.39519741,
        -0.69443167,  0.53619566]])

In [22]:
X_test_scaled

array([[ 1.06082005, -0.31864798,  0.7844722 , ...,  1.05948609,
         0.3684825 ,  0.82516323],
       [-0.26894775, -0.31862521, -0.11364956, ..., -0.27910408,
         0.82610165, -2.42755471],
       [-1.43699466, -0.3150879 , -0.40287521, ..., -1.43350211,
         0.37918829,  0.82275279],
       ...,
       [-1.58351073, -0.3149499 ,  0.16092216, ..., -1.63640912,
         0.57807903, -0.08400875],
       [ 1.34179679, -0.31405408, -0.40849676, ...,  1.37090587,
        -0.45745302,  0.77553274],
       [ 0.02687853, -0.31864804, -0.31804663, ...,  0.02779027,
         0.64740272, -2.41474758]])

# Logistic regression

In [23]:
log_reg = LogisticRegression()

In [24]:
# training the logistic regression model with traiing data
log_reg.fit(X_train_scaled, Y_train)

LogisticRegression()

In [25]:
log_reg.predict(X_train_scaled)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [26]:
log_reg.score(X_train_scaled,Y_train)

0.993661673125494

In [27]:
log_reg.score(X_test_scaled,Y_test)

0.9935758767617174

In [28]:
accuracy = log_reg.score(X_test, Y_test)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.99


# Desicion Tree

In [29]:
D_tree = DecisionTreeClassifier(criterion = 'entropy', max_depth = 4)
D_tree.fit(X_train_scaled,Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [30]:
prediction = D_tree.predict(X_train_scaled)

In [31]:
prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [32]:
D_tree.score(X_train_scaled,Y_train)

0.9946584533518422

In [33]:
D_tree.score(X_test_scaled,Y_test)

0.9944897526365511

In [34]:
accuracy = D_tree.score(X_test, Y_test)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.96
